### ISSUE TITLE
Option to emit the initial observable value

### ISSUE THREAD

**Issue by d6u** [yankodimitrov/SignalKit#1]
First of all, great library, really simple API!

For example:

```
var o1 = ObservableValue("Rose")
s = observe(o1)
    .next { println($0) }
```

If I don't call `dispatch`, the `next` block will never be invoked. Is it possible to have an option to invoke the next block when attached?

**Comment by yankodimitrov** [comment]
Hi,

Actually it was the desired effect to dispatch the current value when adding an observer to ObservableValue. Thanks for pointing out the bug! 

Just released the <code>v0.1.1</code> with the bug fix.

Thanks!

**Comment by d6u** [comment]
Thanks for the quick fix. Do you accept PR to add other methods, e.g. flatMap?

**Comment by yankodimitrov** [comment]
Sure, flatMap will be a great addition.

**Comment by jpmhouston** [comment]
Pardon for digging this back up, but even though I dig the most recent rewrite, it looks like this feature of emitting the initial observable value has not survived. This doesn't much affect my code that does `observe().next() { myupdatemethod() }` since I can call my method separately during load, however it does impact where I'm currently using `'observe().bindTo(...)` for which there's not an obvious thing to call manually.

This is only from looking at the (now much simpler!) code, I might be wrong. Can you verify this has indeed changed since v3.0?

If this is the case, what's a good approach get this behaviour back: maybe add my own extension `SignalType` which adds `bindToAndEmitInitialValue`, or use a new `SignalEmittingInitialValue` (conforming to `SignalType`) instead of `Signal`?

**Comment by yankodimitrov** [comment]
Its functionality moved to `SignalValue` which is a signal that holds its most recent value and when you observe it you will receive right away the current value.

I need to find some time to update the library to Swift 3 and perhaps rework some parts.
If you have any suggestions, please open an issue.

:)
